name: Build document

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install build dependencies
      run: |
        python -m pip install -U pip
        python -m pip install . myst-parser
    - name: Build document
      run: |
        cd docs/
        make html
    - name: Push to GitHub Pages branch
      uses: ftnext/action-push-ghpages@v1.0.0
      with:
        build_dir: docs/_build/html
        github_token: ${{ secrets.GITHUB_TOKEN }}
